### ISSUE TITLE
solr errors are unCaught, resulting in blank page

### ISSUE THREAD

**Issue by milovanderlinden** [City-of-Bloomington/uReport#206]
I have a faulty solr setup. When I run the app and it redirects to tickets, a blank page is shown. In the background php throws an error. This is hard to debug in a docker environment. It might be better to handle the error and provide a human readable error message.

```
::1:53660 [500]: /tickets - Uncaught Apache_Solr_HttpTransportException: '0' Status: Communication Error in /home/miblon/NetBeansProjects/uReport/crm/libraries/solr-php-client/Apache/Solr/Service.php:339
Stack trace:
#0 /home/miblon/NetBeansProjects/uReport/crm/libraries/solr-php-client/Apache/Solr/Service.php(1201): Apache_Solr_Service->_sendRawGet('http://localhos...')
#1 /home/miblon/NetBeansProjects/uReport/crm/Models/Search.php(226): Apache_Solr_Service->search('*:*', 0, 10, Array)
#2 /home/miblon/NetBeansProjects/uReport/crm/Controllers/TicketsController.php(62): Application\Models\Search->query(Array, false)
#3 /home/miblon/NetBeansProjects/uReport/crm/public/index.php(60): Application\Controllers\TicketsController->index()
#4 {main}
  thrown in /home/miblon/NetBeansProjects/uReport/crm/libraries/solr-php-client/Apache/Solr/Service.php on line 339
```

**Comment by inghamn** [comment]
Error handling is admittedly non-existent.  In our production systems I turn on the Skidder reporting, so I can receive emails when the errors occur.
